import type { CSSProperties } from 'react';
import { LoadingState } from '@/components/ui/LoadingState';
import { cssVar, identityToken } from '@/lib/entityColor';
import { SeasonNotes } from './SeasonNotes';
import { SeasonPicker } from './SeasonPicker';
import type { DialCell, TitleCard } from './presenters';
import type { SeasonNotice } from './selectors';

/**
 * **The season masthead** — the top of `/seasons/:year`, and the first thing on the first surface
 * of this product that carries real content.
 *
 * Three elements, in descending order of size, because a surface needs a hierarchy of drama and
 * not just a calm majority:
 *
 * 1. **The year**, at `--display-lg` / `--display-xl`, tabular, and simultaneously the season
 *    picker's trigger (`SeasonPicker`).
 * 2. **The dial** — the whole calendar as one row of ticks. It is not a chart: no scale, no axis,
 *    no d3. It exists because *"24 calendar rows, 22 numbered rounds"* is the most surprising fact
 *    about 2026 and a row of marks in which two are visibly not like the others states it faster
 *    than the sentence underneath ever will.
 * 3. **The title cards** — who won, or who is winning, in each championship. This is the single
 *    most valuable fact about a season, so it is above the fold rather than buried at the top of a
 *    table.
 *
 * **The team colour on a title card is a 3px bar beside a name** (§3.3a.1), never a fill and never
 * a chart mark. `identityToken()` is the only thing that resolves it, and it returns a token name —
 * no hex reaches this file.
 *
 * ---
 *
 * **⚠ No G-15 here, and that is a correction rather than an omission** _(2026-08-07, from
 * Rishabh's capture of the loading window)_.
 *
 * This section used `useSectionReveal`, with the title cards and the dial as staggered
 * `reveal-item`s. A capture taken about a second into a cold load showed the year and the section
 * headings at low opacity and **nothing else on the page** — no rows, no cards. It read as broken,
 * and the diagnosis is not a missing skeleton: the skeletons were rendering and holding their
 * height correctly. **They were inside the reveal, so they started at `opacity: 0`.**
 *
 * Three things were wrong with that, and each is now a rule in `DESIGN_SYSTEM.md` §4.6.1:
 *
 * 1. **G-15 is a scroll reveal, and this section is never scrolled to.** It is the first thing on
 *    the route. There is nothing to reveal *to*.
 * 2. **A loading state must never be animated in.** A skeleton exists to say "this box is coming";
 *    a skeleton fading in says nothing at all for its first 200ms, which is most of the window a
 *    fast query is even visible for.
 * 3. **G-2 already animates the route's content as one block.** Three staggered entrances on one
 *    screen was the reason the page looked like it was assembling itself rather than arriving.
 */

export interface SeasonMastheadProps {
  /** `null` only while a bare `/seasons` resolves its default year from `/api/meta`. */
  year: number | null;
  years: readonly number[];
  /** Null while the season query is in flight. */
  dial: readonly DialCell[] | null;
  driverTitle: TitleCard | null;
  teamTitle: TitleCard | null;
  /** Already filtered to the masthead slot by `noticesFor`. */
  notices: readonly SeasonNotice[];
  /** `10 of 22 rounds complete` — generated by the caller from the payload, never counted here. */
  progressLine: string | null;
  pending: boolean;
  /**
   * The season query failed. The masthead still renders — the year and the picker are the reader's
   * way out, and taking the navigation down with the content is two failures rather than one — but
   * the title cards are dropped rather than shown as skeletons that will never resolve.
   */
  failed?: boolean;
}

export function SeasonMasthead({
  year,
  years,
  dial,
  driverTitle,
  teamTitle,
  notices,
  progressLine,
  pending,
  failed = false,
}: SeasonMastheadProps) {
  return (
    <section className="season-masthead" aria-labelledby="season-title">
      <div className="season-headline">
        <div>
          <p className="season-eyebrow">
            <span className="accent-rule" aria-hidden="true" />
            Season
          </p>
          {/*
           * `SeasonPicker` owns the `h1` — the heading has to wrap the trigger *only*, or its
           * accessible name picks up the two step arrows and its content stops being valid HTML.
           * See the note in that file.
           */}
          <div className="mt-3">
            <SeasonPicker year={year} years={years} headingId="season-title" />
          </div>
        </div>

        {progressLine !== null && <p className="t-sm text-ink-secondary pb-2">{progressLine}</p>}
      </div>

      {dial !== null && dial.length > 0 && year !== null && <SeasonDial cells={dial} year={year} />}

      {notices.length > 0 && <SeasonNotes notices={notices} />}

      {/*
       * Dropped entirely on failure. A skeleton that will never resolve is a promise the surface
       * cannot keep, and the error card below states what actually happened.
       */}
      {!failed && (
        <div className="season-titles">
          {pending ? (
            <>
              <TitleSkeleton />
              <TitleSkeleton />
            </>
          ) : (
            <>
              {driverTitle !== null && <TitleCardView card={driverTitle} />}
              {teamTitle !== null && <TitleCardView card={teamTitle} />}
            </>
          )}
        </div>
      )}
    </section>
  );
}

/**
 * The dial. **One `role="img"` with a single accessible name, not 24 list items** — announcing
 * twenty-four ticks one at a time is worse than useless, and the summary sentence carries the
 * whole meaning. Each tick keeps a `<title>`-free `data-status` for styling only.
 */
function SeasonDial({ cells, year }: { cells: readonly DialCell[]; year: number }) {
  const raced = cells.filter((cell) => cell.status === 'raced').length;
  const cancelled = cells.filter((cell) => cell.status === 'cancelled').length;

  const summary =
    cancelled === 0
      ? `The ${String(year)} calendar: ${String(cells.length)} events, ${String(raced)} raced.`
      : `The ${String(year)} calendar: ${String(cells.length)} events, ${String(raced)} raced, ${String(cancelled)} cancelled.`;

  return (
    <div className="flex flex-col gap-2">
      <div className="season-dial" role="img" aria-label={summary}>
        {cells.map((cell) => (
          <span key={cell.key} className="season-dial-cell" data-status={cell.status} />
        ))}
      </div>
      {/*
       * **One caption, right-aligned, and no axis labels** _(corrected 2026-08-07)_. This carried a
       * lone `01` under the first cell. A single number at one end of a track reads as an axis that
       * failed to finish rendering rather than as a deliberate anchor — and the honest fix is not
       * three labels but none: the ticks are ordinal and equal-width, so a scale adds no reading
       * the caption does not already give. The caption states the count, the raced count and the
       * cancelled count, which is the whole content of the mark.
       */}
      <p className="season-dial-scale" aria-hidden="true">
        {summary}
      </p>
    </div>
  );
}

function TitleCardView({ card }: { card: TitleCard }) {
  return (
    <article
      className="season-title-card"
      style={{ '--identity': cssVar(identityToken(card.colorRef)) } as CSSProperties}
    >
      <p className="season-eyebrow">{card.eyebrow}</p>
      <p className="season-title-name">{card.name}</p>
      <p className="t-xs text-ink-secondary">{card.detail}</p>
      <p className="season-title-figures">
        <span className="season-title-figure">
          <b>{card.points}</b> points
        </span>
        <span className="season-title-figure">
          <b>{card.wins}</b> {card.wins === 1 ? 'win' : 'wins'}
        </span>
      </p>
    </article>
  );
}

/**
 * The skeleton is the card's own box (§7.5), so the masthead cannot reflow when the query
 * resolves. One busy region for the pair, not one per card.
 */
function TitleSkeleton() {
  return (
    <div className="season-title-card" aria-hidden="true">
      <LoadingState announce={false} className="skeleton-title-eyebrow" />
      <LoadingState announce={false} className="skeleton-title-name" />
      <LoadingState announce={false} className="skeleton-title-detail" />
    </div>
  );
}
