import type { Circuit } from './circuit';
import type { Driver } from './driver';
import type { Team } from './team';

/**
 * Valid payloads for the three entity endpoints, used by the schema tests and by the
 * client hook tests.
 *
 * They are hand-written rather than captured from a response on purpose: a fixture
 * captured from the implementation asserts only that the implementation agrees with
 * itself. The figures are real ones a reader can check — **Ascari's 1950 Italian Grand
 * Prix is the trap-17 case verbatim** (two classification rows, one race, second place in
 * the car he took over) and his 1950 season is a genuine no-qualifying, no-fastest-lap
 * era, so the coverage denominators are 0 rather than tidy.
 */

export const driverFixture: Driver = {
  driver: {
    ref: 'ascari',
    code: null,
    forename: 'Alberto',
    surname: 'Ascari',
    nationality: 'Italian',
    countryCode: 'IT',
    permanentCarNumber: null,
    dateOfBirth: '1918-07-13',
  },
  career: {
    firstSeason: 1950,
    lastSeason: 1950,
    seasonsEntered: 1,
    firstRace: {
      year: 1950,
      round: 2,
      name: 'Monaco Grand Prix',
      date: '1950-05-21',
      circuitRef: 'monaco',
      circuitName: 'Circuit de Monaco',
    },
    lastRace: {
      year: 1950,
      round: 7,
      name: 'Italian Grand Prix',
      date: '1950-09-03',
      circuitRef: 'monza',
      circuitName: 'Autodromo Nazionale di Monza',
    },
    ageAtFirstRace: 31,
    ageAtLastRace: 32,
  },
  totals: {
    entries: 3,
    races: 2,
    starts: 2,
    nonStarts: 0,
    wins: 0,
    podiums: 2,
    pointsFinishes: 2,
    poles: 0,
    // Zero, not "no poles" — the era holds no qualifying classification at all.
    racesWithQualifying: 0,
    fastestLaps: 0,
    racesWithFastestLapData: 0,
    dnfs: 0,
    mechanicalDnfs: 0,
    accidentDnfs: 0,
    disqualifications: 0,
    championships: 0,
  },
  seasons: [
    {
      year: 1950,
      teams: [{ ref: 'ferrari', name: 'Ferrari', firstRound: 2, lastRound: 7, entries: 3 }],
      entries: 3,
      starts: 2,
      wins: 0,
      podiums: 2,
      bestFinish: 2,
      points: 11,
      position: 5,
      championshipWins: 0,
      adjustment: 'none',
      isSeasonComplete: true,
      isChampion: false,
    },
  ],
  races: [
    {
      year: 1950,
      round: 2,
      name: 'Monaco Grand Prix',
      date: '1950-05-21',
      circuitRef: 'monaco',
      circuitName: 'Circuit de Monaco',
      teamRef: 'ferrari',
      teamName: 'Ferrari',
      carNumber: 34,
      entries: 1,
      gridPosition: 7,
      gridStatus: 'grid',
      position: 2,
      outcome: 'finished',
      detail: 'Finished',
      isClassified: true,
      points: 6,
      lapsCompleted: 99,
      qualifyingPosition: null,
      qualifyingSession: null,
      roundHasQualifying: false,
      hasFastestLap: false,
      roundHasFastestLapData: false,
      positionsGained: 5,
    },
    {
      // Trap 17: two classification rows folded into one race whose result is the car he
      // was classified in. `entries: 2` is what makes the fold visible.
      year: 1950,
      round: 7,
      name: 'Italian Grand Prix',
      date: '1950-09-03',
      circuitRef: 'monza',
      circuitName: 'Autodromo Nazionale di Monza',
      teamRef: 'ferrari',
      teamName: 'Ferrari',
      carNumber: 48,
      entries: 2,
      gridPosition: 6,
      gridStatus: 'grid',
      position: 2,
      outcome: 'finished',
      detail: 'Finished',
      isClassified: true,
      points: 3,
      lapsCompleted: 80,
      qualifyingPosition: null,
      qualifyingSession: null,
      roundHasQualifying: false,
      hasFastestLap: false,
      roundHasFastestLapData: false,
      positionsGained: 4,
    },
  ],
  gridVsFinish: {
    racesCounted: 2,
    meanPositionsGained: 4.5,
    bestGain: 5,
    worstLoss: 4,
    gained: 2,
    lost: 0,
    held: 0,
    excluded: { unclassified: 0, pitLaneStarts: 0, unknownGrid: 0 },
  },
  qualifyingVsRace: {
    racesCounted: 0,
    meanDelta: null,
    racesWithQualifying: 0,
    meanQualifyingPosition: null,
  },
};

export const teamFixture: Team = {
  team: { ref: 'brawn', name: 'Brawn', nationality: 'British', countryCode: 'GB' },
  career: {
    firstSeason: 2009,
    lastSeason: 2009,
    seasonsEntered: 1,
    firstRace: {
      year: 2009,
      round: 1,
      name: 'Australian Grand Prix',
      date: '2009-03-29',
      circuitRef: 'albert_park',
      circuitName: 'Albert Park Grand Prix Circuit',
    },
    lastRace: {
      year: 2009,
      round: 17,
      name: 'Abu Dhabi Grand Prix',
      date: '2009-11-01',
      circuitRef: 'yas_marina',
      circuitName: 'Yas Marina Circuit',
    },
  },
  totals: { races: 17, entries: 34, wins: 8, podiums: 15, driversUsed: 2, championships: 1 },
  seasons: [
    {
      year: 2009,
      entries: 34,
      races: 17,
      wins: 8,
      podiums: 15,
      bestFinish: 1,
      points: 172,
      position: 1,
      championshipWins: 8,
      adjustment: 'none',
      hasTeamStandings: true,
      isSeasonComplete: true,
      isChampion: true,
      // Race points, never the championship figure above — see `schemas/team.ts`.
      driverRacePointsTotal: 172,
      drivers: [
        {
          driverRef: 'button',
          code: 'BUT',
          forename: 'Jenson',
          surname: 'Button',
          firstRound: 1,
          lastRound: 17,
          entries: 17,
          starts: 17,
          wins: 6,
          podiums: 9,
          bestFinish: 1,
          racePoints: 95,
          racePointsShare: 95 / 172,
        },
        {
          driverRef: 'barrichello',
          code: 'BAR',
          forename: 'Rubens',
          surname: 'Barrichello',
          firstRound: 1,
          lastRound: 17,
          entries: 17,
          starts: 17,
          wins: 2,
          podiums: 6,
          bestFinish: 1,
          racePoints: 77,
          racePointsShare: 77 / 172,
        },
      ],
    },
  ],
};

export const circuitFixture: Circuit = {
  circuit: {
    ref: 'monza',
    name: 'Autodromo Nazionale di Monza',
    locality: 'Monza',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 45.6156,
    longitude: 9.28111,
    altitude: 162,
  },
  firstYear: 1950,
  lastYear: 2024,
  roundsHeld: 2,
  racesWithResults: 2,
  races: [
    {
      year: 2024,
      round: 16,
      name: 'Italian Grand Prix',
      date: '2024-09-01',
      hasResults: true,
      hasLapData: true,
      entries: 20,
      winners: [
        {
          driverRef: 'leclerc',
          code: 'LEC',
          forename: 'Charles',
          surname: 'Leclerc',
          teamRef: 'ferrari',
          teamName: 'Ferrari',
          points: 25,
        },
      ],
      poleSitters: [
        {
          driverRef: 'norris',
          code: 'NOR',
          forename: 'Lando',
          surname: 'Norris',
          session: 'Q3',
        },
      ],
      hasQualifying: true,
    },
    {
      // Pre-1994: results exist, a pole sitter does not, and `hasQualifying` says which.
      year: 1950,
      round: 7,
      name: 'Italian Grand Prix',
      date: '1950-09-03',
      hasResults: true,
      hasLapData: false,
      entries: 29,
      winners: [
        {
          driverRef: 'farina',
          code: null,
          forename: 'Nino',
          surname: 'Farina',
          teamRef: 'alfa',
          teamName: 'Alfa Romeo',
          points: 8,
        },
      ],
      poleSitters: [],
      hasQualifying: false,
    },
  ],
  topDrivers: [
    {
      driverRef: 'leclerc',
      code: 'LEC',
      forename: 'Charles',
      surname: 'Leclerc',
      starts: 1,
      wins: 1,
      podiums: 1,
      bestFinish: 1,
    },
  ],
  topTeams: [{ teamRef: 'ferrari', name: 'Ferrari', races: 1, wins: 1, podiums: 1 }],
};
