import type { CompareData } from './types';

/**
 * ⚠ **A FIXTURE, AND A TEMPORARY ONE.** `GET /api/compare` does not exist yet — this feature was
 * designed and built in parallel with it, deliberately, so that the payload was specified by the
 * surface that needs it rather than discovered afterwards (`DESIGN_SYSTEM.md` §6.6.5's rule, which
 * the entity indexes were rejected for breaking).
 *
 * **Every figure below was queried from `data/f1.db`**, not invented: Hamilton 106 wins and 7
 * titles, Verstappen 71 and 4 through 2026 R10, Fangio 24 wins from 51 starts and 5 titles. The
 * chains reproduce by BFS over 4,637 round-level teammate pairings. Two were checked against the
 * record before anything was drawn: 2016 Hamilton–Rosberg **10–9** over 19 shared finishes, and
 * 1988 Senna–Prost **7–5** over 12.
 *
 * **Delete this file the day the endpoint lands.** `ComparePage` is a pure function of
 * `CompareData` and takes it as a prop, so the swap is one line in `src/routes/Compare.tsx` and
 * nothing in this directory changes.
 */
export const COMPARE_FIXTURE: CompareData = {
  entities: [
    {
      identity: {
        ref: 'hamilton',
        forename: 'Lewis',
        surname: 'Hamilton',
        code: 'HAM',
      },
      colorTeamRef: 'mercedes',
      firstSeason: 2007,
      lastSeason: 2026,
      seasonsEntered: 20,
      totals: {
        races: 390,
        starts: 390,
        wins: 106,
        podiums: 207,
        dnfs: 34,
        classifiedFinishes: 358,
        championships: 7,
      },
      teammates: {
        count: 7,
        race: {
          rated: 324,
          pool: 324,
          a: 189,
          b: 135,
          tied: 0,
        },
        grid: {
          rated: 389,
          pool: 389,
          a: 223,
          b: 166,
          tied: 0,
        },
      },
      seasons: [
        {
          year: 2007,
          teamRefs: ['mclaren'],
          starts: 17,
          wins: 4,
          podiums: 12,
          dnfs: 1,
          championshipPosition: 2,
        },
        {
          year: 2008,
          teamRefs: ['mclaren'],
          starts: 18,
          wins: 5,
          podiums: 10,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 2009,
          teamRefs: ['mclaren'],
          starts: 17,
          wins: 2,
          podiums: 5,
          dnfs: 3,
          championshipPosition: 5,
        },
        {
          year: 2010,
          teamRefs: ['mclaren'],
          starts: 19,
          wins: 3,
          podiums: 9,
          dnfs: 4,
          championshipPosition: 4,
        },
        {
          year: 2011,
          teamRefs: ['mclaren'],
          starts: 19,
          wins: 3,
          podiums: 6,
          dnfs: 3,
          championshipPosition: 5,
        },
        {
          year: 2012,
          teamRefs: ['mclaren'],
          starts: 20,
          wins: 4,
          podiums: 7,
          dnfs: 6,
          championshipPosition: 4,
        },
        {
          year: 2013,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 1,
          podiums: 5,
          dnfs: 1,
          championshipPosition: 4,
        },
        {
          year: 2014,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 11,
          podiums: 16,
          dnfs: 3,
          championshipPosition: 1,
        },
        {
          year: 2015,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 10,
          podiums: 17,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 2016,
          teamRefs: ['mercedes'],
          starts: 21,
          wins: 10,
          podiums: 17,
          dnfs: 2,
          championshipPosition: 2,
        },
        {
          year: 2017,
          teamRefs: ['mercedes'],
          starts: 20,
          wins: 9,
          podiums: 13,
          dnfs: 0,
          championshipPosition: 1,
        },
        {
          year: 2018,
          teamRefs: ['mercedes'],
          starts: 21,
          wins: 11,
          podiums: 17,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 2019,
          teamRefs: ['mercedes'],
          starts: 21,
          wins: 11,
          podiums: 17,
          dnfs: 0,
          championshipPosition: 1,
        },
        {
          year: 2020,
          teamRefs: ['mercedes'],
          starts: 16,
          wins: 11,
          podiums: 14,
          dnfs: 0,
          championshipPosition: 1,
        },
        {
          year: 2021,
          teamRefs: ['mercedes'],
          starts: 22,
          wins: 8,
          podiums: 17,
          dnfs: 1,
          championshipPosition: 2,
        },
        {
          year: 2022,
          teamRefs: ['mercedes'],
          starts: 22,
          wins: 0,
          podiums: 9,
          dnfs: 2,
          championshipPosition: 6,
        },
        {
          year: 2023,
          teamRefs: ['mercedes'],
          starts: 22,
          wins: 0,
          podiums: 6,
          dnfs: 1,
          championshipPosition: 3,
        },
        {
          year: 2024,
          teamRefs: ['mercedes'],
          starts: 24,
          wins: 2,
          podiums: 5,
          dnfs: 2,
          championshipPosition: 7,
        },
        {
          year: 2025,
          teamRefs: ['ferrari'],
          starts: 24,
          wins: 0,
          podiums: 0,
          dnfs: 2,
          championshipPosition: 6,
        },
        {
          year: 2026,
          teamRefs: ['ferrari'],
          starts: 10,
          wins: 1,
          podiums: 5,
          dnfs: 0,
          championshipPosition: 2,
        },
      ],
    },
    {
      identity: {
        ref: 'rosberg',
        forename: 'Nico',
        surname: 'Rosberg',
        code: 'ROS',
      },
      colorTeamRef: 'mercedes',
      firstSeason: 2006,
      lastSeason: 2016,
      seasonsEntered: 11,
      totals: {
        races: 206,
        starts: 206,
        wins: 23,
        podiums: 57,
        dnfs: 31,
        classifiedFinishes: 177,
        championships: 1,
      },
      teammates: {
        count: 5,
        race: {
          rated: 145,
          pool: 145,
          a: 76,
          b: 69,
          tied: 0,
        },
        grid: {
          rated: 206,
          pool: 206,
          a: 127,
          b: 79,
          tied: 0,
        },
      },
      seasons: [
        {
          year: 2006,
          teamRefs: ['williams'],
          starts: 18,
          wins: 0,
          podiums: 0,
          dnfs: 9,
          championshipPosition: 17,
        },
        {
          year: 2007,
          teamRefs: ['williams'],
          starts: 17,
          wins: 0,
          podiums: 0,
          dnfs: 4,
          championshipPosition: 9,
        },
        {
          year: 2008,
          teamRefs: ['williams'],
          starts: 18,
          wins: 0,
          podiums: 2,
          dnfs: 2,
          championshipPosition: 13,
        },
        {
          year: 2009,
          teamRefs: ['williams'],
          starts: 17,
          wins: 0,
          podiums: 0,
          dnfs: 1,
          championshipPosition: 7,
        },
        {
          year: 2010,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 0,
          podiums: 3,
          dnfs: 3,
          championshipPosition: 7,
        },
        {
          year: 2011,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 0,
          podiums: 0,
          dnfs: 2,
          championshipPosition: 7,
        },
        {
          year: 2012,
          teamRefs: ['mercedes'],
          starts: 20,
          wins: 1,
          podiums: 2,
          dnfs: 3,
          championshipPosition: 9,
        },
        {
          year: 2013,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 2,
          podiums: 4,
          dnfs: 3,
          championshipPosition: 6,
        },
        {
          year: 2014,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 5,
          podiums: 15,
          dnfs: 2,
          championshipPosition: 2,
        },
        {
          year: 2015,
          teamRefs: ['mercedes'],
          starts: 19,
          wins: 6,
          podiums: 15,
          dnfs: 1,
          championshipPosition: 2,
        },
        {
          year: 2016,
          teamRefs: ['mercedes'],
          starts: 21,
          wins: 9,
          podiums: 16,
          dnfs: 1,
          championshipPosition: 1,
        },
      ],
    },
    {
      identity: {
        ref: 'max_verstappen',
        forename: 'Max',
        surname: 'Verstappen',
        code: 'VER',
      },
      colorTeamRef: 'red_bull',
      firstSeason: 2015,
      lastSeason: 2026,
      seasonsEntered: 12,
      totals: {
        races: 243,
        starts: 243,
        wins: 71,
        podiums: 130,
        dnfs: 36,
        classifiedFinishes: 210,
        championships: 4,
      },
      teammates: {
        count: 8,
        race: {
          rated: 176,
          pool: 176,
          a: 147,
          b: 29,
          tied: 0,
        },
        grid: {
          rated: 234,
          pool: 234,
          a: 181,
          b: 53,
          tied: 0,
        },
      },
      seasons: [
        {
          year: 2015,
          teamRefs: ['toro_rosso'],
          starts: 19,
          wins: 0,
          podiums: 0,
          dnfs: 5,
          championshipPosition: 12,
        },
        {
          year: 2016,
          teamRefs: ['toro_rosso', 'red_bull'],
          starts: 21,
          wins: 1,
          podiums: 7,
          dnfs: 3,
          championshipPosition: 5,
        },
        {
          year: 2017,
          teamRefs: ['red_bull'],
          starts: 20,
          wins: 2,
          podiums: 4,
          dnfs: 7,
          championshipPosition: 6,
        },
        {
          year: 2018,
          teamRefs: ['red_bull'],
          starts: 21,
          wins: 2,
          podiums: 11,
          dnfs: 4,
          championshipPosition: 4,
        },
        {
          year: 2019,
          teamRefs: ['red_bull'],
          starts: 21,
          wins: 3,
          podiums: 9,
          dnfs: 2,
          championshipPosition: 3,
        },
        {
          year: 2020,
          teamRefs: ['red_bull'],
          starts: 17,
          wins: 2,
          podiums: 11,
          dnfs: 5,
          championshipPosition: 3,
        },
        {
          year: 2021,
          teamRefs: ['red_bull'],
          starts: 22,
          wins: 10,
          podiums: 18,
          dnfs: 3,
          championshipPosition: 1,
        },
        {
          year: 2022,
          teamRefs: ['red_bull'],
          starts: 22,
          wins: 15,
          podiums: 17,
          dnfs: 2,
          championshipPosition: 1,
        },
        {
          year: 2023,
          teamRefs: ['red_bull'],
          starts: 22,
          wins: 19,
          podiums: 21,
          dnfs: 0,
          championshipPosition: 1,
        },
        {
          year: 2024,
          teamRefs: ['red_bull'],
          starts: 24,
          wins: 9,
          podiums: 14,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 2025,
          teamRefs: ['red_bull'],
          starts: 24,
          wins: 8,
          podiums: 15,
          dnfs: 1,
          championshipPosition: 2,
        },
        {
          year: 2026,
          teamRefs: ['red_bull'],
          starts: 10,
          wins: 0,
          podiums: 3,
          dnfs: 3,
          championshipPosition: 7,
        },
      ],
    },
    {
      identity: {
        ref: 'fangio',
        forename: 'Juan',
        surname: 'Fangio',
        code: null,
      },
      colorTeamRef: 'maserati',
      firstSeason: 1950,
      lastSeason: 1958,
      seasonsEntered: 8,
      totals: {
        races: 51,
        starts: 51,
        wins: 24,
        podiums: 35,
        dnfs: 10,
        classifiedFinishes: 41,
        championships: 5,
      },
      teammates: {
        count: 46,
        race: {
          rated: 93,
          pool: 93,
          a: 88,
          b: 5,
          tied: 0,
        },
        grid: {
          rated: 195,
          pool: 195,
          a: 168,
          b: 20,
          tied: 7,
        },
      },
      seasons: [
        {
          year: 1950,
          teamRefs: ['alfa'],
          starts: 6,
          wins: 3,
          podiums: 3,
          dnfs: 3,
          championshipPosition: 2,
        },
        {
          year: 1951,
          teamRefs: ['alfa'],
          starts: 7,
          wins: 3,
          podiums: 5,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 1953,
          teamRefs: ['maserati'],
          starts: 8,
          wins: 1,
          podiums: 4,
          dnfs: 3,
          championshipPosition: 2,
        },
        {
          year: 1954,
          teamRefs: ['maserati', 'mercedes'],
          starts: 8,
          wins: 6,
          podiums: 7,
          dnfs: 0,
          championshipPosition: 1,
        },
        {
          year: 1955,
          teamRefs: ['mercedes'],
          starts: 6,
          wins: 4,
          podiums: 5,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 1956,
          teamRefs: ['ferrari'],
          starts: 7,
          wins: 3,
          podiums: 5,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 1957,
          teamRefs: ['maserati'],
          starts: 7,
          wins: 4,
          podiums: 6,
          dnfs: 1,
          championshipPosition: 1,
        },
        {
          year: 1958,
          teamRefs: ['maserati'],
          starts: 2,
          wins: 0,
          podiums: 0,
          dnfs: 0,
          championshipPosition: 14,
        },
      ],
    },
  ],
  pairs: [
    {
      a: 'hamilton',
      b: 'rosberg',
      relation: 'teammate',
      sharedRaces: 188,
      sameTeamRaces: 78,
      sharedSeasons: [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016],
      sameTeamSeasons: [
        {
          year: 2013,
          teamRef: 'mercedes',
          teamName: 'Mercedes',
        },
        {
          year: 2014,
          teamRef: 'mercedes',
          teamName: 'Mercedes',
        },
        {
          year: 2015,
          teamRef: 'mercedes',
          teamName: 'Mercedes',
        },
        {
          year: 2016,
          teamRef: 'mercedes',
          teamName: 'Mercedes',
        },
      ],
      yearsApart: 0,
      race: {
        rated: 148,
        pool: 188,
        a: 103,
        b: 45,
        tied: 0,
      },
      grid: {
        rated: 188,
        pool: 188,
        a: 132,
        b: 56,
        tied: 0,
      },
    },
    {
      a: 'hamilton',
      b: 'max_verstappen',
      relation: 'contemporary',
      sharedRaces: 242,
      sameTeamRaces: 0,
      sharedSeasons: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
      sameTeamSeasons: [],
      yearsApart: 0,
      race: {
        rated: 200,
        pool: 242,
        a: 103,
        b: 97,
        tied: 0,
      },
      grid: {
        rated: 241,
        pool: 242,
        a: 130,
        b: 111,
        tied: 0,
      },
    },
    {
      a: 'hamilton',
      b: 'fangio',
      relation: 'disjoint',
      sharedRaces: 0,
      sameTeamRaces: 0,
      sharedSeasons: [],
      sameTeamSeasons: [],
      yearsApart: 49,
      race: {
        rated: 0,
        pool: 0,
        a: 0,
        b: 0,
        tied: 0,
      },
      grid: {
        rated: 0,
        pool: 0,
        a: 0,
        b: 0,
        tied: 0,
      },
    },
    {
      a: 'rosberg',
      b: 'max_verstappen',
      relation: 'contemporary',
      sharedRaces: 40,
      sameTeamRaces: 0,
      sharedSeasons: [2015, 2016],
      sameTeamSeasons: [],
      yearsApart: 0,
      race: {
        rated: 31,
        pool: 40,
        a: 24,
        b: 7,
        tied: 0,
      },
      grid: {
        rated: 39,
        pool: 40,
        a: 39,
        b: 0,
        tied: 0,
      },
    },
    {
      a: 'rosberg',
      b: 'fangio',
      relation: 'disjoint',
      sharedRaces: 0,
      sameTeamRaces: 0,
      sharedSeasons: [],
      sameTeamSeasons: [],
      yearsApart: 48,
      race: {
        rated: 0,
        pool: 0,
        a: 0,
        b: 0,
        tied: 0,
      },
      grid: {
        rated: 0,
        pool: 0,
        a: 0,
        b: 0,
        tied: 0,
      },
    },
    {
      a: 'max_verstappen',
      b: 'fangio',
      relation: 'disjoint',
      sharedRaces: 0,
      sameTeamRaces: 0,
      sharedSeasons: [],
      sameTeamSeasons: [],
      yearsApart: 57,
      race: {
        rated: 0,
        pool: 0,
        a: 0,
        b: 0,
        tied: 0,
      },
      grid: {
        rated: 0,
        pool: 0,
        a: 0,
        b: 0,
        tied: 0,
      },
    },
  ],
  chains: [
    {
      a: 'hamilton',
      b: 'max_verstappen',
      length: 3,
      links: [
        {
          from: 'hamilton',
          to: 'button',
          firstYear: 2010,
          lastYear: 2012,
          teams: [
            {
              year: 2010,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
            {
              year: 2011,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
            {
              year: 2012,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
          ],
          race: {
            rated: 41,
            pool: 58,
            a: 26,
            b: 15,
            tied: 0,
          },
          grid: {
            rated: 58,
            pool: 58,
            a: 40,
            b: 18,
            tied: 0,
          },
        },
        {
          from: 'button',
          to: 'perez',
          firstYear: 2013,
          lastYear: 2013,
          teams: [
            {
              year: 2013,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
          ],
          race: {
            rated: 19,
            pool: 19,
            a: 13,
            b: 6,
            tied: 0,
          },
          grid: {
            rated: 19,
            pool: 19,
            a: 10,
            b: 9,
            tied: 0,
          },
        },
        {
          from: 'perez',
          to: 'max_verstappen',
          firstYear: 2021,
          lastYear: 2024,
          teams: [
            {
              year: 2021,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2022,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2023,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2024,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
          ],
          race: {
            rated: 75,
            pool: 90,
            a: 6,
            b: 69,
            tied: 0,
          },
          grid: {
            rated: 86,
            pool: 90,
            a: 13,
            b: 73,
            tied: 0,
          },
        },
      ],
    },
    {
      a: 'hamilton',
      b: 'fangio',
      length: 7,
      links: [
        {
          from: 'hamilton',
          to: 'rosberg',
          firstYear: 2013,
          lastYear: 2016,
          teams: [
            {
              year: 2013,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2014,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2015,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2016,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
          ],
          race: {
            rated: 66,
            pool: 78,
            a: 39,
            b: 27,
            tied: 0,
          },
          grid: {
            rated: 78,
            pool: 78,
            a: 42,
            b: 36,
            tied: 0,
          },
        },
        {
          from: 'rosberg',
          to: 'michael_schumacher',
          firstYear: 2010,
          lastYear: 2012,
          teams: [
            {
              year: 2010,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2011,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2012,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
          ],
          race: {
            rated: 37,
            pool: 58,
            a: 22,
            b: 15,
            tied: 0,
          },
          grid: {
            rated: 58,
            pool: 58,
            a: 43,
            b: 15,
            tied: 0,
          },
        },
        {
          from: 'michael_schumacher',
          to: 'patrese',
          firstYear: 1993,
          lastYear: 1993,
          teams: [
            {
              year: 1993,
              teamRef: 'benetton',
              teamName: 'Benetton',
            },
          ],
          race: {
            rated: 6,
            pool: 16,
            a: 6,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 16,
            pool: 16,
            a: 16,
            b: 0,
            tied: 0,
          },
        },
        {
          from: 'patrese',
          to: 'stommelen',
          firstYear: 1978,
          lastYear: 1978,
          teams: [
            {
              year: 1978,
              teamRef: 'arrows',
              teamName: 'Arrows',
            },
          ],
          race: {
            rated: 3,
            pool: 8,
            a: 3,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 8,
            pool: 8,
            a: 8,
            b: 0,
            tied: 0,
          },
        },
        {
          from: 'stommelen',
          to: 'jack_brabham',
          firstYear: 1970,
          lastYear: 1970,
          teams: [
            {
              year: 1970,
              teamRef: 'brabham',
              teamName: 'Brabham',
            },
          ],
          race: {
            rated: 3,
            pool: 10,
            a: 1,
            b: 2,
            tied: 0,
          },
          grid: {
            rated: 10,
            pool: 10,
            a: 2,
            b: 8,
            tied: 0,
          },
        },
        {
          from: 'jack_brabham',
          to: 'gregory',
          firstYear: 1959,
          lastYear: 1962,
          teams: [
            {
              year: 1959,
              teamRef: 'cooper-climax',
              teamName: 'Cooper-Climax',
            },
            {
              year: 1961,
              teamRef: 'cooper-climax',
              teamName: 'Cooper-Climax',
            },
            {
              year: 1962,
              teamRef: 'lotus-climax',
              teamName: 'Lotus-Climax',
            },
          ],
          race: {
            rated: 4,
            pool: 13,
            a: 4,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 11,
            pool: 13,
            a: 11,
            b: 0,
            tied: 0,
          },
        },
        {
          from: 'gregory',
          to: 'fangio',
          firstYear: 1957,
          lastYear: 1957,
          teams: [
            {
              year: 1957,
              teamRef: 'maserati',
              teamName: 'Maserati',
            },
          ],
          race: {
            rated: 4,
            pool: 4,
            a: 0,
            b: 4,
            tied: 0,
          },
          grid: {
            rated: 4,
            pool: 4,
            a: 0,
            b: 4,
            tied: 0,
          },
        },
      ],
    },
    {
      a: 'rosberg',
      b: 'max_verstappen',
      length: 4,
      links: [
        {
          from: 'rosberg',
          to: 'hamilton',
          firstYear: 2013,
          lastYear: 2016,
          teams: [
            {
              year: 2013,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2014,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2015,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2016,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
          ],
          race: {
            rated: 66,
            pool: 78,
            a: 27,
            b: 39,
            tied: 0,
          },
          grid: {
            rated: 78,
            pool: 78,
            a: 36,
            b: 42,
            tied: 0,
          },
        },
        {
          from: 'hamilton',
          to: 'button',
          firstYear: 2010,
          lastYear: 2012,
          teams: [
            {
              year: 2010,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
            {
              year: 2011,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
            {
              year: 2012,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
          ],
          race: {
            rated: 41,
            pool: 58,
            a: 26,
            b: 15,
            tied: 0,
          },
          grid: {
            rated: 58,
            pool: 58,
            a: 40,
            b: 18,
            tied: 0,
          },
        },
        {
          from: 'button',
          to: 'perez',
          firstYear: 2013,
          lastYear: 2013,
          teams: [
            {
              year: 2013,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
          ],
          race: {
            rated: 19,
            pool: 19,
            a: 13,
            b: 6,
            tied: 0,
          },
          grid: {
            rated: 19,
            pool: 19,
            a: 10,
            b: 9,
            tied: 0,
          },
        },
        {
          from: 'perez',
          to: 'max_verstappen',
          firstYear: 2021,
          lastYear: 2024,
          teams: [
            {
              year: 2021,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2022,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2023,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2024,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
          ],
          race: {
            rated: 75,
            pool: 90,
            a: 6,
            b: 69,
            tied: 0,
          },
          grid: {
            rated: 86,
            pool: 90,
            a: 13,
            b: 73,
            tied: 0,
          },
        },
      ],
    },
    {
      a: 'rosberg',
      b: 'fangio',
      length: 6,
      links: [
        {
          from: 'rosberg',
          to: 'michael_schumacher',
          firstYear: 2010,
          lastYear: 2012,
          teams: [
            {
              year: 2010,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2011,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
            {
              year: 2012,
              teamRef: 'mercedes',
              teamName: 'Mercedes',
            },
          ],
          race: {
            rated: 37,
            pool: 58,
            a: 22,
            b: 15,
            tied: 0,
          },
          grid: {
            rated: 58,
            pool: 58,
            a: 43,
            b: 15,
            tied: 0,
          },
        },
        {
          from: 'michael_schumacher',
          to: 'patrese',
          firstYear: 1993,
          lastYear: 1993,
          teams: [
            {
              year: 1993,
              teamRef: 'benetton',
              teamName: 'Benetton',
            },
          ],
          race: {
            rated: 6,
            pool: 16,
            a: 6,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 16,
            pool: 16,
            a: 16,
            b: 0,
            tied: 0,
          },
        },
        {
          from: 'patrese',
          to: 'stommelen',
          firstYear: 1978,
          lastYear: 1978,
          teams: [
            {
              year: 1978,
              teamRef: 'arrows',
              teamName: 'Arrows',
            },
          ],
          race: {
            rated: 3,
            pool: 8,
            a: 3,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 8,
            pool: 8,
            a: 8,
            b: 0,
            tied: 0,
          },
        },
        {
          from: 'stommelen',
          to: 'jack_brabham',
          firstYear: 1970,
          lastYear: 1970,
          teams: [
            {
              year: 1970,
              teamRef: 'brabham',
              teamName: 'Brabham',
            },
          ],
          race: {
            rated: 3,
            pool: 10,
            a: 1,
            b: 2,
            tied: 0,
          },
          grid: {
            rated: 10,
            pool: 10,
            a: 2,
            b: 8,
            tied: 0,
          },
        },
        {
          from: 'jack_brabham',
          to: 'gregory',
          firstYear: 1959,
          lastYear: 1962,
          teams: [
            {
              year: 1959,
              teamRef: 'cooper-climax',
              teamName: 'Cooper-Climax',
            },
            {
              year: 1961,
              teamRef: 'cooper-climax',
              teamName: 'Cooper-Climax',
            },
            {
              year: 1962,
              teamRef: 'lotus-climax',
              teamName: 'Lotus-Climax',
            },
          ],
          race: {
            rated: 4,
            pool: 13,
            a: 4,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 11,
            pool: 13,
            a: 11,
            b: 0,
            tied: 0,
          },
        },
        {
          from: 'gregory',
          to: 'fangio',
          firstYear: 1957,
          lastYear: 1957,
          teams: [
            {
              year: 1957,
              teamRef: 'maserati',
              teamName: 'Maserati',
            },
          ],
          race: {
            rated: 4,
            pool: 4,
            a: 0,
            b: 4,
            tied: 0,
          },
          grid: {
            rated: 4,
            pool: 4,
            a: 0,
            b: 4,
            tied: 0,
          },
        },
      ],
    },
    {
      a: 'max_verstappen',
      b: 'fangio',
      length: 8,
      links: [
        {
          from: 'max_verstappen',
          to: 'perez',
          firstYear: 2021,
          lastYear: 2024,
          teams: [
            {
              year: 2021,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2022,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2023,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
            {
              year: 2024,
              teamRef: 'red_bull',
              teamName: 'Red Bull',
            },
          ],
          race: {
            rated: 75,
            pool: 90,
            a: 69,
            b: 6,
            tied: 0,
          },
          grid: {
            rated: 86,
            pool: 90,
            a: 73,
            b: 13,
            tied: 0,
          },
        },
        {
          from: 'perez',
          to: 'button',
          firstYear: 2013,
          lastYear: 2013,
          teams: [
            {
              year: 2013,
              teamRef: 'mclaren',
              teamName: 'McLaren',
            },
          ],
          race: {
            rated: 19,
            pool: 19,
            a: 6,
            b: 13,
            tied: 0,
          },
          grid: {
            rated: 19,
            pool: 19,
            a: 9,
            b: 10,
            tied: 0,
          },
        },
        {
          from: 'button',
          to: 'barrichello',
          firstYear: 2006,
          lastYear: 2009,
          teams: [
            {
              year: 2006,
              teamRef: 'honda',
              teamName: 'Honda',
            },
            {
              year: 2007,
              teamRef: 'honda',
              teamName: 'Honda',
            },
            {
              year: 2008,
              teamRef: 'honda',
              teamName: 'Honda',
            },
            {
              year: 2009,
              teamRef: 'brawn',
              teamName: 'Brawn',
            },
          ],
          race: {
            rated: 47,
            pool: 70,
            a: 31,
            b: 16,
            tied: 0,
          },
          grid: {
            rated: 70,
            pool: 70,
            a: 34,
            b: 36,
            tied: 0,
          },
        },
        {
          from: 'barrichello',
          to: 'cesaris',
          firstYear: 1994,
          lastYear: 1994,
          teams: [
            {
              year: 1994,
              teamRef: 'jordan',
              teamName: 'Jordan',
            },
          ],
          race: {
            rated: 0,
            pool: 2,
            a: 0,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 1,
            pool: 2,
            a: 0,
            b: 1,
            tied: 0,
          },
        },
        {
          from: 'cesaris',
          to: 'giacomelli',
          firstYear: 1980,
          lastYear: 1982,
          teams: [
            {
              year: 1980,
              teamRef: 'alfa',
              teamName: 'Alfa Romeo',
            },
            {
              year: 1982,
              teamRef: 'alfa',
              teamName: 'Alfa Romeo',
            },
          ],
          race: {
            rated: 3,
            pool: 18,
            a: 2,
            b: 1,
            tied: 0,
          },
          grid: {
            rated: 18,
            pool: 18,
            a: 10,
            b: 8,
            tied: 0,
          },
        },
        {
          from: 'giacomelli',
          to: 'mario_andretti',
          firstYear: 1981,
          lastYear: 1981,
          teams: [
            {
              year: 1981,
              teamRef: 'alfa',
              teamName: 'Alfa Romeo',
            },
          ],
          race: {
            rated: 6,
            pool: 15,
            a: 2,
            b: 4,
            tied: 0,
          },
          grid: {
            rated: 15,
            pool: 15,
            a: 7,
            b: 8,
            tied: 0,
          },
        },
        {
          from: 'mario_andretti',
          to: 'bonnier',
          firstYear: 1969,
          lastYear: 1969,
          teams: [
            {
              year: 1969,
              teamRef: 'lotus-ford',
              teamName: 'Lotus-Ford',
            },
          ],
          race: {
            rated: 0,
            pool: 1,
            a: 0,
            b: 0,
            tied: 0,
          },
          grid: {
            rated: 1,
            pool: 1,
            a: 1,
            b: 0,
            tied: 0,
          },
        },
        {
          from: 'bonnier',
          to: 'fangio',
          firstYear: 1957,
          lastYear: 1958,
          teams: [
            {
              year: 1957,
              teamRef: 'maserati',
              teamName: 'Maserati',
            },
            {
              year: 1958,
              teamRef: 'maserati',
              teamName: 'Maserati',
            },
          ],
          race: {
            rated: 2,
            pool: 5,
            a: 0,
            b: 2,
            tied: 0,
          },
          grid: {
            rated: 5,
            pool: 5,
            a: 0,
            b: 5,
            tied: 0,
          },
        },
      ],
    },
  ],
  people: {
    hamilton: {
      ref: 'hamilton',
      forename: 'Lewis',
      surname: 'Hamilton',
      code: 'HAM',
    },
    button: {
      ref: 'button',
      forename: 'Jenson',
      surname: 'Button',
      code: 'BUT',
    },
    perez: {
      ref: 'perez',
      forename: 'Sergio',
      surname: 'Pérez',
      code: 'PER',
    },
    max_verstappen: {
      ref: 'max_verstappen',
      forename: 'Max',
      surname: 'Verstappen',
      code: 'VER',
    },
    rosberg: {
      ref: 'rosberg',
      forename: 'Nico',
      surname: 'Rosberg',
      code: 'ROS',
    },
    michael_schumacher: {
      ref: 'michael_schumacher',
      forename: 'Michael',
      surname: 'Schumacher',
      code: 'MSC',
    },
    patrese: {
      ref: 'patrese',
      forename: 'Riccardo',
      surname: 'Patrese',
      code: null,
    },
    stommelen: {
      ref: 'stommelen',
      forename: 'Rolf',
      surname: 'Stommelen',
      code: null,
    },
    jack_brabham: {
      ref: 'jack_brabham',
      forename: 'Jack',
      surname: 'Brabham',
      code: null,
    },
    gregory: {
      ref: 'gregory',
      forename: 'Masten',
      surname: 'Gregory',
      code: null,
    },
    fangio: {
      ref: 'fangio',
      forename: 'Juan',
      surname: 'Fangio',
      code: null,
    },
    barrichello: {
      ref: 'barrichello',
      forename: 'Rubens',
      surname: 'Barrichello',
      code: 'BAR',
    },
    cesaris: {
      ref: 'cesaris',
      forename: 'Andrea',
      surname: 'de Cesaris',
      code: null,
    },
    giacomelli: {
      ref: 'giacomelli',
      forename: 'Bruno',
      surname: 'Giacomelli',
      code: null,
    },
    mario_andretti: {
      ref: 'mario_andretti',
      forename: 'Mario',
      surname: 'Andretti',
      code: null,
    },
    bonnier: {
      ref: 'bonnier',
      forename: 'Jo',
      surname: 'Bonnier',
      code: null,
    },
  },
  archive: [
    {
      year: 1950,
      rounds: 7,
    },
    {
      year: 1951,
      rounds: 8,
    },
    {
      year: 1952,
      rounds: 8,
    },
    {
      year: 1953,
      rounds: 9,
    },
    {
      year: 1954,
      rounds: 9,
    },
    {
      year: 1955,
      rounds: 7,
    },
    {
      year: 1956,
      rounds: 8,
    },
    {
      year: 1957,
      rounds: 8,
    },
    {
      year: 1958,
      rounds: 11,
    },
    {
      year: 1959,
      rounds: 9,
    },
    {
      year: 1960,
      rounds: 10,
    },
    {
      year: 1961,
      rounds: 8,
    },
    {
      year: 1962,
      rounds: 9,
    },
    {
      year: 1963,
      rounds: 10,
    },
    {
      year: 1964,
      rounds: 10,
    },
    {
      year: 1965,
      rounds: 10,
    },
    {
      year: 1966,
      rounds: 9,
    },
    {
      year: 1967,
      rounds: 11,
    },
    {
      year: 1968,
      rounds: 12,
    },
    {
      year: 1969,
      rounds: 11,
    },
    {
      year: 1970,
      rounds: 13,
    },
    {
      year: 1971,
      rounds: 11,
    },
    {
      year: 1972,
      rounds: 12,
    },
    {
      year: 1973,
      rounds: 15,
    },
    {
      year: 1974,
      rounds: 15,
    },
    {
      year: 1975,
      rounds: 14,
    },
    {
      year: 1976,
      rounds: 16,
    },
    {
      year: 1977,
      rounds: 17,
    },
    {
      year: 1978,
      rounds: 16,
    },
    {
      year: 1979,
      rounds: 15,
    },
    {
      year: 1980,
      rounds: 14,
    },
    {
      year: 1981,
      rounds: 15,
    },
    {
      year: 1982,
      rounds: 16,
    },
    {
      year: 1983,
      rounds: 15,
    },
    {
      year: 1984,
      rounds: 16,
    },
    {
      year: 1985,
      rounds: 16,
    },
    {
      year: 1986,
      rounds: 16,
    },
    {
      year: 1987,
      rounds: 16,
    },
    {
      year: 1988,
      rounds: 16,
    },
    {
      year: 1989,
      rounds: 16,
    },
    {
      year: 1990,
      rounds: 16,
    },
    {
      year: 1991,
      rounds: 16,
    },
    {
      year: 1992,
      rounds: 16,
    },
    {
      year: 1993,
      rounds: 16,
    },
    {
      year: 1994,
      rounds: 16,
    },
    {
      year: 1995,
      rounds: 17,
    },
    {
      year: 1996,
      rounds: 16,
    },
    {
      year: 1997,
      rounds: 17,
    },
    {
      year: 1998,
      rounds: 16,
    },
    {
      year: 1999,
      rounds: 16,
    },
    {
      year: 2000,
      rounds: 17,
    },
    {
      year: 2001,
      rounds: 17,
    },
    {
      year: 2002,
      rounds: 17,
    },
    {
      year: 2003,
      rounds: 16,
    },
    {
      year: 2004,
      rounds: 18,
    },
    {
      year: 2005,
      rounds: 19,
    },
    {
      year: 2006,
      rounds: 18,
    },
    {
      year: 2007,
      rounds: 17,
    },
    {
      year: 2008,
      rounds: 18,
    },
    {
      year: 2009,
      rounds: 17,
    },
    {
      year: 2010,
      rounds: 19,
    },
    {
      year: 2011,
      rounds: 19,
    },
    {
      year: 2012,
      rounds: 20,
    },
    {
      year: 2013,
      rounds: 19,
    },
    {
      year: 2014,
      rounds: 19,
    },
    {
      year: 2015,
      rounds: 19,
    },
    {
      year: 2016,
      rounds: 21,
    },
    {
      year: 2017,
      rounds: 20,
    },
    {
      year: 2018,
      rounds: 21,
    },
    {
      year: 2019,
      rounds: 21,
    },
    {
      year: 2020,
      rounds: 17,
    },
    {
      year: 2021,
      rounds: 22,
    },
    {
      year: 2022,
      rounds: 22,
    },
    {
      year: 2023,
      rounds: 22,
    },
    {
      year: 2024,
      rounds: 24,
    },
    {
      year: 2025,
      rounds: 24,
    },
    {
      year: 2026,
      rounds: 22,
    },
  ],
};
